### ISSUE TITLE
Scroll offset

### ISSUE THREAD

**Issue by josetamu** [CodyHouse/cd-table-of-contents-changelog#7]
Hey there,

Is there a way to apply an offset when scrolling? I could see the component uses window.innerHeight/2 which makes the new section visible when it enters the center of the viewport.
But I'm looking to make it visible as soon as it enters the viewport, or any other customizable value. Changing only window.innerHeight/2 seems to break things.

Thanks in advance :)

**Comment by claudia-romano** [comment]
Hi there, in the `getVisibleSection` function, rather than using `window.innerHeight/2`, use `window.innerHeight`. This will update the toc navigation as soon as a new section enters the viewport. We'll make sure to make this option customizable. 

Feel free to reopen the issue if you are still having problems.
